name: Build iOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'

      - name: Gerar constants.dart
        run: |
          cat > lib/core/constants.dart << EOF
          class AppConstants {
            static const String groqApiKey = '${{ secrets.GROQ_API_KEY }}';
            static const String unsplashApiKey = '${{ secrets.UNSPLASH_API_KEY }}';
            static const String supabaseUrl = '${{ secrets.SUPABASE_URL }}';
            static const String supabaseAnonKey = '${{ secrets.SUPABASE_ANON_KEY }}';
          }
          EOF

      - run: flutter pub get

      - run: flutter build ios --debug --simulator

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphonesimulator
